name: mobile
description: mantap project tros

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # blocs and something
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  hydrated_bloc: ^9.0.0

  # ui
  lottie: ^2.0.0
  google_fonts: ^3.0.1
  flutter_slidable: ^2.0.0
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.2.16

  # utils
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  intl:
  android_intent_plus: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  ios: true

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
